### ISSUE TITLE
Xarray.combine by coords with Docker

### ISSUE THREAD

**Issue by A-Spork** [GeoSoftII2020-21/GeoSoftII_DataServer#5]
When dockerised the wrappermethod(Collection_Sentinel_SST_Data)  throws an error:

[Errormessage.txt](https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/files/5843075/Errormessage.txt)

The same command on a lokal windowsmachine  goes threw without an error

**Comment by nuest** [comment]
Can you please provide the exact runtime environments on your Windows machine an in the container? All package versions, Python version, etc.

**Comment by A-Spork** [comment]
The runtime environment of my lokal machine is attatched.

[runtime environment lokal machine.txt](https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/files/5844421/runtime.environment.lokal.machine.txt)

The runtime environment for the server will be added shortly by a member of the server-dev team

**Comment by ghost** [comment]
The Docker Specification:
We specified all used  packages  for this  microservice in the [req.txt](https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/blob/Server/req.txt). If no version is specified  the most recent is installed. Packages are installed with pip. We  use python 3.8.6 as specified in the [dockerfile](https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/blob/Server/Dockerfile). Docker is running on a  windows  machine with the wsl2 backend.

**Comment by nuest** [comment]
"The most recent version is installed" - the differences that might occur on different systems here might help you to track down the error, so that's why I asked for the exact versions.

**Comment by nuest** [comment]
I recommend you compare the two lists and see if anything sticks out.

If you'd like me to take an actual look, please prepare a minimal reproducible example. Thanks!

**Comment by ghost** [comment]
In the docker-compose branch from our GeoSoft2_Project Repository in the minExample Directory is a Example script which reproduces the error. The job.json file is also required. (https://github.com/GeoSoftII2020-21/GeoSoftII_Projekt/tree/Docker-compose)  It needs the requests and docker package installed and also docker and docker compose. Also at least 12gb ram are needed. The whole log from the Server is printed in the Commandline (if exectuted in a commandline). It does not Terminate the the Server after its completion!

**Comment by nuest** [comment]
Did you see https://github.com/pydata/xarray/issues/4213 ?

**Comment by nuest** [comment]
The problematic function is used a few times in the code: https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/search?q=xr.combine_by_coords

The problematic line in the code seems to be https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/blob/main/Wrapper/Collections_Sentinel2_SST_Data.py#L583

You should be able to force the error by writing a test that calls the function `merge_datacubes(ds_merge)` with the input data that you use.

**Comment by A-Spork** [comment]
Error solved by replacing the xArray.merge_by_coords with the xArray.open_mfdataset, which is based on the merge_by_coord function
