### ISSUE TITLE
KeyError cloudcoveragepercentage - downloading from the API

### ISSUE THREAD

**Issue by A-Spork** [GeoSoftII2020-21/GeoSoftII_DataServer#6]
When dockerised the Wrappermethod throws an error, when using the Sentinel Collection:

[Errormessage.txt](https://github.com/GeoSoftII2020-21/GeoSoftII_DataServer/files/5843093/Errormessage.txt)

The same command on a lokal windowsmachine goes threw without an error

**Comment by nuest** [comment]
Have you checked the issue tracker of `sentinelsat` module for any hints?

**Comment by A-Spork** [comment]
Issue was created, when the function sort_values() was given 0 inputs,

removed funtion from code, when updating the downloadData function anyways
